// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hjucsvqobunayxbrlkpk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhqdWNzdnFvYnVuYXl4YnJsa3BrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzkwOTEzOTYsImV4cCI6MjA1NDY2NzM5Nn0.AoLYXRQJZblxhltkxaGY-AqJiqwYETGjW0h5UsNMsT8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);